from copy import deepcopy
from dataclasses import asdict
import hashlib
import json
from pathlib import Path
from unittest.mock import patch

import pytest
from pydantic import ValidationError

from backend.rulesets import compiler
from backend.rulesets.contracts import RuleSetContent
from backend.rulesets.errors import RuleSetValidationError


# Captured by the unmodified compiler at 1f98721 before the T2 extraction.
# This fixture is an old-output oracle, not an output regenerated by the new core.
FIXTURE_PATH = Path(__file__).parent / "fixtures" / "ruleset_compiler_t2_baseline.json"
BASELINE = json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))
CASES = BASELINE["cases"]
SUCCESS_CASES = [case for case in CASES if "output" in case]
PROMPT_KEYS = (
    "image_prompt", "frame_prompt", "comment_prompt_template", "fusion_prompt_template",
)


def test_frozen_baseline_provenance():
    assert BASELINE["baseline_head"] == "1f9872117fa8dbd8e34ff2d7e6ad73be4a4b5761"
    assert hashlib.sha256(FIXTURE_PATH.read_bytes()).hexdigest() == (
        "e612bf12fb9ed9ff41a94e5ea7afccaf53c464fe29d7706c84cadef51c637d69"
    )


@pytest.mark.parametrize("case", CASES, ids=lambda case: case["name"])
def test_historical_t2_artifact_integrity_and_current_formal_contract(case):
    if case["name"] == "unsupported_domain":
        assert case["error"]["message"] == "RuleSet Foundation pilot only supports the gambling domain"
        compiler.compile_ruleset_content(case["revision"]["snapshot"])
        return
    with patch.dict(compiler.FIXED_PROMPT_LIMITS, case.get("limits", {})):
        if "error" in case:
            with pytest.raises(RuleSetValidationError) as caught:
                compiler.compile_ruleset_revision(
                    deepcopy(case["revision"]),
                    audit_policy=deepcopy(case["audit_policy"]), **case["context"],
                )
            assert type(caught.value).__name__ == case["error"]["type"]
            if case["name"].startswith("budget_"):
                assert str(caught.value).split(" characters:")[0] == case["error"]["message"].split(" characters:")[0]
            else:
                assert str(caught.value) == case["error"]["message"]
            return
        actual = compiler.compile_ruleset_revision(
            deepcopy(case["revision"]),
            audit_policy=deepcopy(case["audit_policy"]), **case["context"],
        )
    historical = case["output"]
    assert actual["rule_snapshot"] == historical["rule_snapshot"]
    assert actual["audit_policy_snapshot"] == historical["audit_policy_snapshot"]
    profile = deepcopy(historical["prompt_profile_snapshot"])
    version = profile.pop("prompt_version")
    assert version == "gambling-v1-" + hashlib.sha256(compiler.canonical_json(profile).encode()).hexdigest()[:16]
    payload = {key: historical[key] for key in ("schema_version", "audit_policy_snapshot", "rule_snapshot", "prompt_profile_snapshot")}
    payload["audit_policy"] = payload.pop("audit_policy_snapshot")
    payload["ruleset_revision"] = historical["rule_snapshot"]["ruleset_ref"]
    payload.update({key: profile[key] for key in ("system_template_version", "compiler_version")})
    assert historical["config_hash"] == hashlib.sha256(compiler.canonical_json(payload).encode()).hexdigest()
    assert actual["config_hash"] != historical["config_hash"]
    for key in PROMPT_KEYS:
        assert actual["prompt_profile_snapshot"][key] != historical["prompt_profile_snapshot"][key]


@pytest.mark.parametrize("case", SUCCESS_CASES, ids=lambda case: case["name"])
def test_content_core_preserves_t2_mechanics_and_current_formal_seam(case):
    content = deepcopy(case["revision"]["snapshot"])
    original = deepcopy(content)
    actual = compiler.compile_ruleset_content(content)
    assert actual == compiler.compile_ruleset_content(RuleSetContent.model_validate(content))
    assert actual == compiler.compile_ruleset_content(deepcopy(content))
    assert content == original
    expected = case["output"]
    formal = compiler.compile_ruleset_revision(case["revision"], audit_policy=case["audit_policy"])
    assert actual.prompt_profile_snapshot == formal["prompt_profile_snapshot"]
    assert actual.decision_rules == expected["rule_snapshot"]["decision_rules"]
    assert actual.stage_routes == expected["rule_snapshot"]["stage_routes"]
    assert actual.general_exemptions == expected["rule_snapshot"]["general_exemptions"]
    assert set(asdict(actual)) == {
        "prompt_profile_snapshot", "decision_rules", "stage_routes", "general_exemptions",
    }


@pytest.mark.parametrize("name", ["identity", "policy"])
def test_formal_context_changes_only_formal_output(name):
    base = SUCCESS_CASES[0]
    changed = next(case for case in CASES if case["name"] == name)
    assert compiler.compile_ruleset_content(base["revision"]["snapshot"]) == (
        compiler.compile_ruleset_content(changed["revision"]["snapshot"])
    )
    before = compiler.compile_ruleset_revision(base["revision"], audit_policy=base["audit_policy"])
    after = compiler.compile_ruleset_revision(changed["revision"], audit_policy=changed["audit_policy"])
    assert before["prompt_profile_snapshot"] == after["prompt_profile_snapshot"]
    assert before["config_hash"] != after["config_hash"]
    assert before["rule_snapshot"]["ruleset_ref"]["content_hash"] == (
        after["rule_snapshot"]["ruleset_ref"]["content_hash"]
    )
    assert after["rule_snapshot"] == changed["output"]["rule_snapshot"]


@pytest.mark.parametrize("case", [
    case for case in CASES
    if case["name"] in {"compiler_version", "system_template_version"}
    or case["name"].startswith("budget_")
], ids=lambda case: case["name"])
def test_core_keeps_versions_and_stage_budget_failures(case):
    with patch.dict(compiler.FIXED_PROMPT_LIMITS, case.get("limits", {})):
        with pytest.raises(RuleSetValidationError) as caught:
            compiler.compile_ruleset_content(case["revision"]["snapshot"], **case["context"])
    assert str(caught.value).split(" characters:")[0] == case["error"]["message"].split(" characters:")[0]


def test_core_validates_content_and_does_not_share_mutable_results():
    content = deepcopy(SUCCESS_CASES[0]["revision"]["snapshot"])
    content["categories"][0]["rules"][0]["enabled"] = 1
    with pytest.raises(ValidationError):
        compiler.compile_ruleset_content(content)
    content = SUCCESS_CASES[0]["revision"]["snapshot"]
    first = compiler.compile_ruleset_content(content)
    second = compiler.compile_ruleset_content(content)
    first.decision_rules.clear()
    first.prompt_profile_snapshot["image_prompt"] = "changed"
    assert second == compiler.compile_ruleset_content(content)
